apiVersion: v1
kind: Service
metadata:
  name: lcd-collector
  namespace: {{ .Values.namespace }}
  labels:
    app: lcd-collector
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  selector:
    app: lcd-collector
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
